# -*- coding: utf-8 -*-
"""mentalhealth_chatboat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q7sLAVlrjq7iC2aypZ4PJton6iZ3Z011
"""

!pip install transformers datasets scikit-learn gradio

import pandas as pd
from sentence_transformers import SentenceTransformer, util
import gradio as gr

# Load the mental health dataset
df = pd.read_csv("/content/Mental_Health_FAQ.csv")  # Replace filename if different

# Ensure correct column names
df.columns = ["Question_ID","Questions", "Answers"]  # Rename if needed

# Convert to lists
questions = df["Questions"].tolist()
answers = df["Answers"].tolist()

df.columns

# Load a Sentence-BERT model (small, accurate, fast)
model = SentenceTransformer('all-MiniLM-L6-v2')

# Encode all questions in dataset
question_embeddings = model.encode(questions, convert_to_tensor=True)

def chatbot_response(user_input):
    # Encode user's input
    user_embedding = model.encode(user_input, convert_to_tensor=True)

    # Compute similarity between user input and all dataset questions
    similarity_scores = util.cos_sim(user_embedding, question_embeddings)[0]

    # Find the index of the most similar question
    top_match_idx = similarity_scores.argmax().item()

    # Return the corresponding answer
    return answers[top_match_idx]

gr.Interface(
    fn=chatbot_response,
    inputs=gr.Textbox(lines=2, placeholder="Ask a mental health question..."),
    outputs="text",
    title="🧠 Mental Health Support Chatbot",
    description="Ask me mental health related questions like:\n- What are symptoms of depression?\n- Can anxiety be cured?\n- What to do if I feel low?"
).launch()